<div class='message error'>
    <h3 style="font-weight: bold; color: red; text-transform: uppercase">Attention, there has been an Error</h3>
    <p style="font-family: monospace">$Error</p>

    <p style="font-weight: bold; margin-top: 2rem">This is an error generated by the META API!</p>
    <p>This element will not be visible in the frontend because of the given error.</p>
</div>
